### ISSUE TITLE
loadCSS

### ISSUE THREAD

**Issue by webchaz** [angular-ui/ui-tinymce#108]
Is it possible to call the loadCSS (http://www.tinymce.com/wiki.php/API3:method.tinymce.dom.DOMUtils.loadCSS) using this plugin?  Since it's not an option, but a function?

**Comment by wesleycho** [comment]
It is possible to call it manually (although keep in mind that this library supports 4.x, so it uses [this api](http://www.tinymce.com/wiki.php/api4:method.tinymce.dom.DOMUtils.loadCSS)).

I do not believe that it should be part of this library, since it is user config. I would recommend writing a wrapper service around the `tinymce` global and have it control loading on app boot.
