### ISSUE TITLE
Tags are messed up.

### ISSUE THREAD

**Issue by thatguyyoulove** [angular-ui/ui-tinymce#127]
Looks like the tags are a bit messed up for Bower. Checking out the latest version checks out 0.0.5, but this points to the 0.0.5 tag rather than the v0.0.5 tag. Thus, 3 months of commits are not included.

Would be good to remove the ambiguity of having two 0.0.5 tags. Suggest making a single 0.0.6 tag with latest commit, or adjusting bower.json to resolve to correct tag.

**Comment by Joni-Aaltonen** [comment]
Yes, please fix tagging.

**Comment by rbecheras** [comment]
+1

**Comment by rbecheras** [comment]
I just fixed the issue in my fork: http://github.com/rbecheras/ui-tinymce
* I versionned the bower and npm package to 0.0.6
* I tagged it v0.0.6
* I also registred the bower package `angular-ui-tinymce-v0.0.6`
* So you can install it instead of the official while the angular-ui team merge my pull request and propagate the tag

    $ bower remove angular-ui-tinymce --save
    $ bower install angular-ui-tinymce-v0.0.6 --save

* THAT FIX TEMPORARY #112 and #127.
* I WILL UNREGISTER THIS PACKAGE WHEN ANGULAR-UI TEAM WILL FIXED IT TOO

**Comment by wesleycho** [comment]
I just deleted the 0.0.5 tag, this should work as expected now.
