### ISSUE TITLE
would like to add a default image style 

### ISSUE THREAD

**Issue by mhhonline** [angular-ui/ui-tinymce#148]
thanks for your great work. 
I have a concern, i cannot edit the image style currently. i can see "Source", "Image description", "Dimensions" but i don't want to have the dimension. instead, i would like to have a style="max-width:100%;height:auto;" this will enable me to have the image as big as my screen size. 

Regards,
Mohammed

**Comment by deeg** [comment]
This is something which is controlled by TinyMCE and not really this library. Off the top of my head I'm not sure TinyMCE offers a way to edit it, but I'm sure they do.

If you believe there is an issue regarding this library, please re-open a new issue with a Plunker demonstrating it. Otherwise, please seek help from the folks over at TinyMCE.
