### ISSUE TITLE
read only mode not working properly

### ISSUE THREAD

**Issue by JFSolorzano** [angular-ui/ui-tinymce#152]
when you set `readonly = 1` tinymce only disables everything, but still display the toolbar and menu options...

**Comment by longzheng** [comment]
I ran into a similar problem when dynamically disabling TinyMCE.

I fixed this by modifying how the ```toggleDisable``` function runs by adding in a few new rules that sets some additional styles.

```javascript
function toggleDisable(disabled) {
            ensureInstance();

            if (tinyInstance) {

				// get the elements
            	var body = tinyInstance.getBody();
            	var container = tinyInstance.getContainer();
            	var toolbar = angular.element(container).find('.mce-toolbar');

				// set the body contenteditable attribute to prevent editing
            	body.setAttribute('contenteditable', !disabled);

				// set the cursor
	            var cursor = disabled ? "not-allowed" : "";
	            tinymce.DOM.setStyle(body,      "cursor", cursor);
	            tinymce.DOM.setStyle(container, "cursor", cursor);

				// prevent any pointer events to the whole container
	            tinymce.DOM.setStyle(container, "pointer-events", disabled ? "none" : "auto");

				// fade out the toolbar
	            tinymce.DOM.setStyle(toolbar, "opacity", disabled ? "0.2" : "1");
            }
        }
```

This is refactored from the current function.

**Comment by deeg** [comment]
Can you please update the issue with a Fiddle or Plunker?

I had a similar issue which I will get fixed in the next release where enabling readonly mode and inline editing would hide the toolbar but still allow editing due to contenteditable being set to true (#175)

I have not however seen the issue where readonly being set to true still displays the toolbar.

Will be happy to look into fixing it once the issue has been updated.

**Comment by deeg** [comment]
Closing this ticket due to inactivity. If you still have an issue please feel free to open a new issue with a plunker attached.
