### ISSUE TITLE
Clear undo history

### ISSUE THREAD

**Issue by qjie2006** [angular-ui/ui-tinymce#157]
I added two lines of code to clear the undo history, is it the right place to add?

 ngModel.$render = function() {
          if (!tinyInstance) {
            tinyInstance = tinymce.get(attrs.id);
          }
          if (tinyInstance) {
              tinyInstance.setContent(ngModel.$viewValue || '');
              tinyInstance.undoManager.clear(); //clear up undo history
              tinyInstance.nodeChanged();       //update UI states
          }
        };

**Comment by deeg** [comment]
Can you give more of a description of what the issue is? It may be the right place.

Is the issue that if you destroy and re-create an instance the undo history remains? It might be better to clear the history on the destroy event.

If you could also include a Plunker or Fiddle that would be great. I will take a brief look into the issue as well and fix if I can re-create.

**Comment by deeg** [comment]
Closing this ticket due to inactivity. If you are still having problems, please feel free to open a new issue with an attached plunker reproducing it.
