### ISSUE TITLE
Original content wiped out & inline option broken it seems

### ISSUE THREAD

**Issue by phillyDesignr** [angular-ui/ui-tinymce#221]
The content within the containing element is being wiped out and not the same behavior as regular TinyMCE

Also ***{inline: true}*** cause it to break

http://codepen.io/z3vin/pen/jWzMww

**Comment by deeg** [comment]
The inline works if you change the textarea to a div. This is not an issue with this library but a limitation of tinymce itself.

As for the initial content, rather than putting it in the text area, assign it as a string to the value in ng-model and it works just fine. What is happening is since you have ng-model pointing to a variable with no data, it is changing the value of the editor to that.

I am going to close this issue as there is no bug, but feel free to ask questions, and I will help you more here the best I can.
