### ISSUE TITLE
ui tinymce 2 way binding not working

### ISSUE THREAD

**Issue by lulzimfazlija2** [angular-ui/ui-tinymce#223]
I have fixed it in localhost but the problem is when I upload my site to production(Heroku in my case) the problem still remains...

The way I have fixed it locally was by adding a single line of code to directive in return statement:

    priority: 10

But this I cannot add it to Heroku as the Heroku itself installs the dependencies automatically when deploying the app and I cant edit the file (well I can edit if I want it manually but that's every time i deploy my app on different server I should add that piece of code manually which I dont want to)... I would rather like to find a better solution to this!

Is there any other way I can fix this? or a way I can edit my app on Heroku directly?

**Comment by deeg** [comment]
Can you put up a plunker demonstrating how the 2 way data binding is not working?

#146 adds a priority to the directive but I have not seen a good use case where it is actually needed yet. If you could post a plunker maybe I could recommend a different solution.

If you need to modify the code, I would fork this library and make the changes you need, and then use that instead of this library on your app.

**Comment by lulzimfazlija2** [comment]
Ok, I noticed something else also, it binds the textarea if I do initialize a value to the scope variable for ex: $scope.name = "test"; but when I try to initialize that $scope.name from inside a service call like this:

`ResourceService.showBySessionId(id).then(function (response) {
                    $scope.name = response.data.data[0].content;
                }).catch(function (error) {
                    $scope.result = error;
                });` 

it does not work, and I am sure response.data.data[0].content has a value

**Comment by lulzimfazlija2** [comment]
@deeg, this issue is not making problem only for me, but for lot's of people out there, and I do not see a reason why this has to not be fixed added that line of code priority: 10 to the directive, also I dont think there needs to be a plunker code sample as I already told you exactly the problem..

thnx

**Comment by deeg** [comment]
So you are saying the second issue is fixed with the priority also?

The thing is I don't want to add a priority arbitrarily. I have not encountered a situation where I need it yet.

While you have told me what is going on, I do not have the time to set up the code to try it out myself. If you set up a Plunker I'm more than happy to take a look for you, and add the priority if it really is the only fix.

**Comment by lulzimfazlija2** [comment]
@deeg Can you look at this plunker sample.. I added ui-tinymce library but the textareat does not become rich text editor, dont know why...

https://plnkr.co/edit/QDXNYgC2KWNoEmILx1xK

This is a similiar cas like mine... when I do call a service the textarea doest fill...

**Comment by lulzimfazlija2** [comment]
Ok, I came up with a better solution than I had, added a new directive outside bower folder, call it as <textarea ui-tinymce-custom="tinymceOptions"  ng-model="res.resource.content"></textarea> where here I have priority:10 added its like custom directive for tinymce... No best solution but better I can say... thnx

**Comment by deeg** [comment]
If you look at the console, you can see why the Plunker is not working. 

> Refused to execute script from 'https://raw.githubusercontent.com/angular-ui/ui-tinymce/master/src/tinymce.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Going to close this issue. If you think you find a bug, please open a new issue with a plunker demonstrating the problem.
