### ISSUE TITLE
<br data-mce-bogus="1">

### ISSUE THREAD

**Issue by Jules2010** [angular-ui/ui-tinymce#307]
I've been reading related issues however nothing has led me to a solution.

I've tried setting format to raw.

However this doesn't work for me when using inline = true.

Any suggestions?

Thanks in advance.

**Comment by rbecheras** [comment]
You question isn't clear at all... Or it's me. But I don't understand it.
Plus, it seems it isn't an issue but a request for technical support.
For this purpose, please create a question on stackoverflow instead of posting an issue on github, which is made for development purpose or bug tracking. Even if you are maybe in face of a bug, for now it is not clear at all. So please in a first time, clarify the situation posting an issue on stackoverflow:

> http://stackoverflow.com/questions/ask

You can use the following tags:

- angular-ui-tinymce
- tinymce
- angularjs
- javascript

**Comment by rbecheras** [comment]
@deeg I think you can close this issue.
