### ISSUE TITLE
control is always dirty

### ISSUE THREAD

**Issue by graphicsxp** [angular-ui/ui-tinymce#48]
The control is bound to the model as shown below.

`<textarea id="comment" name="comment" ui-tinymce="tinymceOptions" ng-model="comment"></textarea>`

when I set a watch on 'comment', I can see the value going from undefined to some value whenever the data come back from the server. But then the control becomes dirty.

How to prevent that  ?

**Comment by stephanie-dm** [comment]
Why is this issue closed when the problem is not fixed? I tried with tinymce 4.0.25 and the original problem (form marked dirty as soon as the tinymce-control is loaded). I obviously don't want to make changes in the tinymce code, because after a "bower update" my changes will be gone! And I don't want to start maintaining my own version of tinymce...

**Comment by Joni-Aaltonen** [comment]
Has there been any good solution to this, other than hacking your tinymce.js?
